### ISSUE TITLE
Config parameters do not show up in zwave config UI in home assistant

### ISSUE THREAD

**Issue by partofthething** [InovelliUSA/OpenZWave#4]
Hi. Not entirely sure if this is a @InovelliUSA problem or a [Home Assistant ](https://github.com/home-assistant/) problem, but since https://github.com/OpenZWave/open-zwave/pull/1934 is still open, I doubt anyone else is going to be willing to try to debug besides you and I.

I manually applied the new config entries from that PR to my openzwave config because I just got my LZW30-SN in the mail today and wanted to try it out. I got it installed and paired fine. It shows up in the Home Assistant system and I can control the switch and see the power and energy sensors. Excellent. 

But, I cannot change the config entries from the Home Assistant Z-Wave configuration UI. I really want to fiddle with the LED and button. The drop-down for the parameters is empty: 

![image](https://user-images.githubusercontent.com/5360219/65381055-99cf8100-dc9d-11e9-9ba7-60fa942707cd.png)

Notably, this is also the case for my outdoor switch (a NZW96).

Possibly related (config files not being applied?), both my inovelli devices have names like `Inovelli Unknown: type=6000, id=6000 ` rather than the name in the config file (`NZW96 1-Channel Outdoor Smart Plug`)

**Comment by InovelliUSA** [comment]
Hi @partofthething, let's see if we can figure this out. First off, what method are you using to manually apply the config? What I did was replace the manufacturer_specific.xml from the repository. Then I added the Inovelli xml config files in the appropriate folder. Then included the switch. 

![hassio00](https://user-images.githubusercontent.com/37669481/65476077-f4eca980-de3e-11e9-95cd-dc96ea7de873.PNG)
![hassio01](https://user-images.githubusercontent.com/37669481/65476087-fae28a80-de3e-11e9-8fb9-234e5a12d197.PNG)
![hassio02](https://user-images.githubusercontent.com/37669481/65476090-fd44e480-de3e-11e9-8220-b5f223769a5a.PNG)
![hassio03](https://user-images.githubusercontent.com/37669481/65476094-ffa73e80-de3e-11e9-9e81-5df951e1d553.PNG)
![hassio04](https://user-images.githubusercontent.com/37669481/65476097-02099880-de3f-11e9-9c5e-0316b030923f.PNG)
![hassio05](https://user-images.githubusercontent.com/37669481/65476100-046bf280-de3f-11e9-9e73-5b5d4ccf2741.PNG)

**Comment by partofthething** [comment]
Oh nice. Yours is working as I'd expect. I merged the config files as you did but, now that you mention it in detail, I merged the configs _after_ including the node. I'll remove it and re-add and I'm sure I'll get what youre getting. Sorry for the trouble. 

EDIT: Yup, working amazingly now. Wow I love this thing.
