### ISSUE TITLE
lzw31.xml and lzw31-sn.xml config parameters don't match documentation

### ISSUE THREAD

**Issue by roblamoreaux** [InovelliUSA/OpenZWave#7]
I just installed an LZW31-SN and got it working with Home Assistant by copying these config files to the config directory. This is working for the most part but I noticed that the config parameter description for parameters 1-4 do not match the manual that came with the switch. The manual lists them as:
1.   Dimming speed from switch
2.   Dimming speed Z-Wave
3.   Ramp Rate from switch
4.   Ramp rate Z_Wave

The config file has 1 and 2 swapped and 3 and 4 swapped. The manual seems to match the function of the dimmer.

**Comment by InovelliUSA** [comment]
Hi there, thank you for reaching out. Turns out that there is a misprint in the manual that we will fix in future printings. Thanks again!

It is supposed to be:

1. Dimming speed
2. Dimming speed from switch
3. Ramp Rate 
4. Ramp Rate from switch
